-- Create page_chats table for storing chat conversations per page per user
CREATE TABLE IF NOT EXISTS "public"."page_chats" (
    "id" bigint NOT NULL,
    "page_id" integer NOT NULL,
    "user_id" uuid NOT NULL,
    "messages" jsonb DEFAULT '[]'::jsonb,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- Add primary key
ALTER TABLE "public"."page_chats" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."page_chats_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Add primary key constraint
ALTER TABLE ONLY "public"."page_chats"
    ADD CONSTRAINT "page_chats_pkey" PRIMARY KEY ("id");

-- Add unique constraint to ensure one chat per page per user
ALTER TABLE ONLY "public"."page_chats"
    ADD CONSTRAINT "page_chats_page_user_unique" UNIQUE ("page_id", "user_id");

-- Add foreign key constraints
ALTER TABLE ONLY "public"."page_chats"
    ADD CONSTRAINT "page_chats_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "public"."pages"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."page_chats"
    ADD CONSTRAINT "page_chats_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

-- Add indexes for performance
CREATE INDEX "idx_page_chats_page_id" ON "public"."page_chats" USING "btree" ("page_id");
CREATE INDEX "idx_page_chats_user_id" ON "public"."page_chats" USING "btree" ("user_id");
CREATE INDEX "idx_page_chats_updated_at" ON "public"."page_chats" USING "btree" ("updated_at");

-- Add trigger for updated_at
CREATE OR REPLACE TRIGGER "update_page_chats_modtime" 
    BEFORE UPDATE ON "public"."page_chats" 
    FOR EACH ROW 
    EXECUTE FUNCTION "public"."update_modified_column"();

-- Enable RLS
ALTER TABLE "public"."page_chats" ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Users can only access their own chats
CREATE POLICY "page_chats_select_policy" ON "public"."page_chats" 
    FOR SELECT TO "authenticated" 
    USING (("user_id" = "auth"."uid"()));

CREATE POLICY "page_chats_insert_policy" ON "public"."page_chats" 
    FOR INSERT TO "authenticated" 
    WITH CHECK (("user_id" = "auth"."uid"()));

CREATE POLICY "page_chats_update_policy" ON "public"."page_chats" 
    FOR UPDATE TO "authenticated" 
    USING (("user_id" = "auth"."uid"())) 
    WITH CHECK (("user_id" = "auth"."uid"()));

CREATE POLICY "page_chats_delete_policy" ON "public"."page_chats" 
    FOR DELETE TO "authenticated" 
    USING (("user_id" = "auth"."uid"()));

-- Grant permissions
GRANT ALL ON TABLE "public"."page_chats" TO "anon";
GRANT ALL ON TABLE "public"."page_chats" TO "authenticated";
GRANT ALL ON TABLE "public"."page_chats" TO "service_role";

GRANT ALL ON SEQUENCE "public"."page_chats_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."page_chats_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."page_chats_id_seq" TO "service_role";
