-- Create flashcards table for storing user flashcards per book
CREATE TABLE IF NOT EXISTS "public"."flashcards" (
    "id" bigint NOT NULL,
    "book_id" integer NOT NULL,
    "user_id" uuid NOT NULL,
    "front" text NOT NULL,
    "back" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- Add primary key
ALTER TABLE "public"."flashcards" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."flashcards_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Add primary key constraint
ALTER TABLE ONLY "public"."flashcards"
    ADD CONSTRAINT "flashcards_pkey" PRIMARY KEY ("id");

-- Add foreign key constraints
ALTER TABLE ONLY "public"."flashcards"
    ADD CONSTRAINT "flashcards_book_id_fkey" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."flashcards"
    ADD CONSTRAINT "flashcards_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

-- Add indexes for performance
CREATE INDEX "idx_flashcards_book_id" ON "public"."flashcards" USING "btree" ("book_id");
CREATE INDEX "idx_flashcards_user_id" ON "public"."flashcards" USING "btree" ("user_id");
CREATE INDEX "idx_flashcards_updated_at" ON "public"."flashcards" USING "btree" ("updated_at");

-- Add trigger for updated_at
CREATE OR REPLACE TRIGGER "update_flashcards_modtime" 
    BEFORE UPDATE ON "public"."flashcards" 
    FOR EACH ROW 
    EXECUTE FUNCTION "public"."update_modified_column"();

-- Enable RLS
ALTER TABLE "public"."flashcards" ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Users can only access their own flashcards
CREATE POLICY "flashcards_select_policy" ON "public"."flashcards" 
    FOR SELECT TO "authenticated" 
    USING (("user_id" = "auth"."uid"()));

CREATE POLICY "flashcards_insert_policy" ON "public"."flashcards" 
    FOR INSERT TO "authenticated" 
    WITH CHECK (("user_id" = "auth"."uid"()));

CREATE POLICY "flashcards_update_policy" ON "public"."flashcards" 
    FOR UPDATE TO "authenticated" 
    USING (("user_id" = "auth"."uid"())) 
    WITH CHECK (("user_id" = "auth"."uid"()));

CREATE POLICY "flashcards_delete_policy" ON "public"."flashcards" 
    FOR DELETE TO "authenticated" 
    USING (("user_id" = "auth"."uid"()));

-- Grant permissions
GRANT ALL ON TABLE "public"."flashcards" TO "anon";
GRANT ALL ON TABLE "public"."flashcards" TO "authenticated";
GRANT ALL ON TABLE "public"."flashcards" TO "service_role";

GRANT ALL ON SEQUENCE "public"."flashcards_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."flashcards_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."flashcards_id_seq" TO "service_role";
